### ISSUE TITLE
Publier régulièrement sur #blabla les news

### ISSUE THREAD

**Issue by youknowriad** [algeriatech/dz-community-bot#10]
On pourrait publier les Top News Dyalna tous les matins automatiquement sur #blabla

**Comment by houssem-yahiaoui** [comment]
I'm enhancing the showcasing of the news, it will be nice to automatically post items !

**Comment by houssem-yahiaoui** [comment]
@youknowriad is there any specific timing for the broadcast to be ?

**Comment by youknowriad** [comment]
I guess every morning like at 9h

**Comment by youknowriad** [comment]
Hint: we could use this https://github.com/kelektiv/node-cron

**Comment by houssem-yahiaoui** [comment]
Event this one, https://github.com/node-schedule/node-schedule

**Comment by houssem-yahiaoui** [comment]
mentioned in #24
