### ISSUE TITLE
Utiliser l'API Dyalna Jobs pour récupérer les dernières offres d'emploi TIC en Algérie

### ISSUE THREAD

**Issue by youknowriad** [algeriatech/dz-community-bot#9]
Voici l'URL de l'API à appeler pour les jobs TIC `http://jobs.dyalna.com/jobs/api.php/job?category=1&page=1`

**Comment by houssem-yahiaoui** [comment]
Seems wonderful !and can be a nice added to the jobs sections.

**Comment by houssem-yahiaoui** [comment]
resolved over #15
